{
 "title": "Erigon Internals",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Blocks execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"execution\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Exec v3: txs/s ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "txs apply:  {{instance}}"
    }
   ]
  },
  {
   "title": "Prune, seconds",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prune_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{type}} "
    }
   ]
  },
  {
   "title": "pruning availability, steps",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domain_prunable{instance=~\"$instance\",type=\"domain\"}",
     "legendFormat": "{{instance}}-{{type}}-{{table}}"
    },
    {
     "expr": "domain_prunable{instance=~\"$instance\",type=\"history\",table!=\"commitment\"}/1562500",
     "legendFormat": "{{instance}}-{{type}}-{{table}}"
    }
   ]
  },
  {
   "title": "Sync Stages progress rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sync{instance=~\"$instance\",stage=\"execution\"}[$rate_interval])",
     "legendFormat": "{{ stage }}:  {{instance}}"
    }
   ]
  },
  {
   "title": "State: Collate/Prune/Merge/Commitment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(domain_collation_size{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "collated [domain]: {{instance}}"
    },
    {
     "expr": "irate(domain_collation_hist_size{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "collated [history]: {{instance}}"
    },
    {
     "expr": "sum(rate(domain_commitment_keys[$rate_interval])) by (instance)",
     "legendFormat": "keys committed: {{instance}}"
    },
    {
     "expr": "irate(domain_commitment_updates{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commitment node updates: {{instance}}"
    },
    {
     "expr": "irate(domain_commitment_updates_applied{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commitment trie node updates: {{instance}}"
    },
    {
     "expr": "irate(domain_prune_size{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pruned keys [{{type}}]: {{instance}}"
    }
   ]
  },
  {
   "title": "State: running collate/merge/prune",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "domain_running_merges{instance=~\"$instance\"}",
     "legendFormat": "running merges: {{instance}}"
    },
    {
     "expr": "domain_running_collations{instance=~\"$instance\"}",
     "legendFormat": "running collations: {{instance}}"
    },
    {
     "expr": "domain_pruning_progress{instance=~\"$instance\"}",
     "legendFormat": "running prunes: {{instance}}"
    },
    {
     "expr": "domain_running_commitment{instance=~\"$instance\"}",
     "legendFormat": "running commitment: {{instance}}"
    },
    {
     "expr": "domain_running_files_building{instance=~\"$instance\"}",
     "legendFormat": "running files building: {{instance}}"
    },
    {
     "expr": "domain_wal_flushes{instance=~\"$instance\"}",
     "legendFormat": "WAL flushes {{instance}}"
    }
   ]
  },
  {
   "title": "Block Execution speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chain_execution_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{instance}}"
    }
   ]
  },
  {
   "title": "State: timins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(domain_collate_took_sum{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "collation took: {{instance}}"
    },
    {
     "expr": "rate(domain_step_took_sum{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "step took: {{instance}}"
    },
    {
     "expr": "rate(domain_prune_took_sum{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "prune took [{{type}}]: {{instance}}"
    },
    {
     "expr": "rate(domain_commitment_took_sum{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commitment took: {{instance}}"
    },
    {
     "expr": "rate(domain_commitment_write_took_sum{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commitment update write took: {{instance}}"
    }
   ]
  },
  {
   "title": "Exec v3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(exec_repeats{instance=~\"$instance\"}[$rate_interval])/rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "repeats: {{instance}}"
    },
    {
     "expr": "rate(exec_triggers{instance=~\"$instance\"}[$rate_interval])/rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "triggers: {{instance}}"
    }
   ]
  },
  {
   "title": "Block execution delays",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "block_consumer_delay{type=\"header_download\",instance=~\"$instance\",quantile=\"$quantile\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "block_consumer_delay{type=\"body_download\",instance=~\"$instance\",quantile=\"$quantile\"}",
     "legendFormat": "body: {{instance}}"
    },
    {
     "expr": "block_consumer_delay{type=\"pre_execution\",instance=~\"$instance\",quantile=\"$quantile\"}",
     "legendFormat": "execution_start: {{instance}}"
    },
    {
     "expr": "block_consumer_delay{type=\"post_execution\",instance=~\"$instance\",quantile=\"$quantile\"}",
     "legendFormat": "execution_end: {{instance}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_wall_clock\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_wall_clock: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "sync: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_cpu_time\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_cpu_time: {{instance}}"
    },
    {
     "expr": "db_gc_self_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_xtime: {{instance}}"
    },
    {
     "expr": "db_gc_work_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "work_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_slef_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "self_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_work_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_xtime: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(db_pgops{phase=\"newly\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "newly: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"cow\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cow: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"clone\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"split\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"merge\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "merge: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"spill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"wops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"unspill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcrloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcrloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcwloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcwloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcxpages\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcxpages: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"msync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "msync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"fsync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "fsync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"minicore\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "minicore: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"prefault\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "prefault: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_overflow{instance=~\"$instance\"}",
     "legendFormat": "gc_overflow: {{instance}}"
    },
    {
     "expr": "exec_steps_in_db{instance=~\"$instance\"}/100",
     "legendFormat": "exec_steps_in_db: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "hard: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "db_gc{phase=\"work_rxpages\", instance=~\"$instance\"}",
     "legendFormat": "work_rxpages: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_rsteps\", instance=~\"$instance\"}",
     "legendFormat": "self_rsteps: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"wloop\", instance=~\"$instance\"}",
     "legendFormat": "wloop: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"coalescences\", instance=~\"$instance\"}",
     "legendFormat": "coalescences: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"wipes\", instance=~\"$instance\"}",
     "legendFormat": "wipes: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"flushes\", instance=~\"$instance\"}",
     "legendFormat": "flushes: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"kicks\", instance=~\"$instance\"}",
     "legendFormat": "kicks: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_rsteps\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_rsteps: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_xpages\", instance=~\"$instance\"}",
     "legendFormat": "self_xpages: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_majflt\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_majflt: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_majflt\", instance=~\"$instance\"}",
     "legendFormat": "gc_self_majflt: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_counter\", instance=~\"$instance\"}",
     "legendFormat": "gc_self_counter: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_counter\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_counter: {{instance}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rusage Total (\"last value\" - \"first value\" on selected period)",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "process_io_read_syscalls_total{instance=~\"$instance\"}",
     "legendFormat": "process_io_read_syscalls_total: {{instance}}"
    },
    {
     "expr": "process_io_write_syscalls_total{instance=~\"$instance\"}",
     "legendFormat": "process_io_write_syscalls_total: {{instance}}"
    },
    {
     "expr": "process_minor_pagefaults_total{instance=~\"$instance\"}",
     "legendFormat": "process_minor_pagefaults_total: {{instance}}"
    },
    {
     "expr": "process_major_pagefaults_total{instance=~\"$instance\"}",
     "legendFormat": "process_major_pagefaults_total: {{instance}}"
    },
    {
     "expr": "process_io_storage_read_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "process_io_storage_read_bytes_total: {{instance}}"
    },
    {
     "expr": "process_io_storage_written_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "process_io_storage_written_bytes_total: {{instance}}"
    },
    {
     "expr": "db_pgops_newly{instance=~\"$instance\"}",
     "legendFormat": "pgops_newly: {{instance}}"
    },
    {
     "expr": "db_pgops_cow{instance=~\"$instance\"}",
     "legendFormat": "pgops_cow: {{instance}}"
    },
    {
     "expr": "db_pgops_clone{instance=~\"$instance\"}",
     "legendFormat": "pgops_clone: {{instance}}"
    },
    {
     "expr": "db_pgops_split{instance=~\"$instance\"}",
     "legendFormat": "pgops_split: {{instance}}"
    },
    {
     "expr": "db_pgops_merge{instance=~\"$instance\"}",
     "legendFormat": "pgops_merge: {{instance}}"
    },
    {
     "expr": "db_pgops_spill{instance=~\"$instance\"}",
     "legendFormat": "pgops_spill: {{instance}}"
    },
    {
     "expr": "db_pgops_unspill{instance=~\"$instance\"}",
     "legendFormat": "pgops_unspill: {{instance}}"
    },
    {
     "expr": "db_pgops_wops{instance=~\"$instance\"}",
     "legendFormat": "pgops_wops: {{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "cgo calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cgo_calls_count: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "threads: {{instance}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_inuse: {{ instance }}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mspan_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mcache_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc: {{ instance }}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
    }
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident mem: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_mallocs_total: {{ instance }}"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_frees_total: {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pool_process_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "process_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_add_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "add_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_new_block{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "new_block: {{ instance }}"
    },
    {
     "expr": "pool_write_to_db{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write_to_db: {{ instance }}"
    },
    {
     "expr": "pool_propagate_to_new_peer{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_to_new_peer: {{ instance }}"
    },
    {
     "expr": "pool_propagate_new_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_new_txs: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pool_process_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_process_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_add_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_add_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_new_block_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_new_block_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_write_to_db_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_p2p_out{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"txpool\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache rps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "targets": [
    {
     "expr": "rate(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ result }}: {{ instance }} "
    },
    {
     "expr": "rate(cache_timeout_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "timeout: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pool_write_to_db_bytes{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_bytes: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "DB begin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_begin_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "db_begin_seconds: {{ method }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    },
    {
     "expr": "cache_code_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_keys: {{ instance }} "
    },
    {
     "expr": "cache_code_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_list: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 124 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    },
    {
     "expr": "sum(delta(cache_code_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_code_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "code hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    },
    {
     "expr": "rate(p2p_egress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "egress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  }
 ]
}